spring.application.name=Repository
spring.datasource.url=jdbc:postgresql://localhost:5432/${data.sql}
spring.datasource.username=${postgresql}
spring.datasource.password=${password}

spring.jpa.show-sql=true
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=create

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
